### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by keflavich** [keflavich/despotic#1]
```
$ python setup.py install
/orange/adamginsburg/miniconda3/envs/python39/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
Failed to load libpwind... trying to compile it
g++ -std=c++11   -Ofast -fopenmp -DNDEBUG -DHAVE_INLINE -MMD -MP -fPIC   -c -o pwind_geom.o pwind_geom.cpp
In file included from pwind_geom.cpp:2:
pwind_util.H:9:10: fatal error: gsl/gsl_sf_erf.h: No such file or directory
    9 | #include <gsl/gsl_sf_erf.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [pwind_geom.o] Error 1
Traceback (most recent call last):
  File "/blue/adamginsburg/adamginsburg/repos/despotic/despotic/winds/pwind_interface.py", line 18, in <module>
    libpwind = npct.load_library("libpwind", libdir)
  File "/home/adamginsburg/.local/lib/python3.9/site-packages/numpy/ctypeslib.py", line 154, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/blue/adamginsburg/adamginsburg/repos/despotic/setup.py", line 30, in <module>
    from despotic import __version__ as version
  File "/blue/adamginsburg/adamginsburg/repos/despotic/despotic/__init__.py", line 28, in <module>
    from . import winds
  File "/blue/adamginsburg/adamginsburg/repos/despotic/despotic/winds/__init__.py", line 4, in <module>
    from .pwind import pwind
  File "/blue/adamginsburg/adamginsburg/repos/despotic/despotic/winds/pwind.py", line 24, in <module>
    from .pwind_interface import libpwind
  File "/blue/adamginsburg/adamginsburg/repos/despotic/despotic/winds/pwind_interface.py", line 22, in <module>
    libpwind = npct.load_library("libpwind", libdir)
  File "/home/adamginsburg/.local/lib/python3.9/site-packages/numpy/ctypeslib.py", line 154, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
```

**Comment by keflavich** [comment]
`/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/include/gsl/gsl_sf_erf.h` exists and is on the include path

**Comment by keflavich** [comment]
`export C_INCLUDE_PATH=/blue/adamginsburg/adamginsburg/miniconda3/envs/python39/include:$C_INCLUDE_PATH` solves it - needs to be specifically the C_INCLUDE_PATH.  Apparently this isn't set by conda?

**Comment by keflavich** [comment]
actually this is the right thing to do:
```
module load gcc
module load gsl
export C_INCLUDE_PATH=/apps/gcc/9.3.0/gsl/2.6/include
```
